/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/commands': RouteRecordInfo<'/admin/commands', '/admin/commands', Record<never, never>, Record<never, never>>,
    '/admin/cron-jobs': RouteRecordInfo<'/admin/cron-jobs', '/admin/cron-jobs', Record<never, never>, Record<never, never>>,
    '/admin/extensions': RouteRecordInfo<'/admin/extensions', '/admin/extensions', Record<never, never>, Record<never, never>>,
    '/admin/home': RouteRecordInfo<'/admin/home', '/admin/home', Record<never, never>, Record<never, never>>,
    '/admin/logs': RouteRecordInfo<'/admin/logs', '/admin/logs', Record<never, never>, Record<never, never>>,
    '/admin/migrations': RouteRecordInfo<'/admin/migrations', '/admin/migrations', Record<never, never>, Record<never, never>>,
    '/admin/permissions': RouteRecordInfo<'/admin/permissions', '/admin/permissions', Record<never, never>, Record<never, never>>,
    '/admin/settings': RouteRecordInfo<'/admin/settings', '/admin/settings', Record<never, never>, Record<never, never>>,
    '/admin/tables': RouteRecordInfo<'/admin/tables', '/admin/tables', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
