/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/commands': RouteRecordInfo<'/commands', '/commands', Record<never, never>, Record<never, never>>,
    '/cron-jobs': RouteRecordInfo<'/cron-jobs', '/cron-jobs', Record<never, never>, Record<never, never>>,
    '/extensions': RouteRecordInfo<'/extensions', '/extensions', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logs': RouteRecordInfo<'/logs', '/logs', Record<never, never>, Record<never, never>>,
    '/migrations': RouteRecordInfo<'/migrations', '/migrations', Record<never, never>, Record<never, never>>,
    '/permissions': RouteRecordInfo<'/permissions', '/permissions', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/tables': RouteRecordInfo<'/tables', '/tables', Record<never, never>, Record<never, never>>,
    '/tables/[name]': RouteRecordInfo<'/tables/[name]', '/tables/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
  }
}
